language: elixir
matrix:
  include:
    - elixir: 1.7
      otp_release: 22.0
    - elixir: 1.8
      otp_release: 22.0
    - elixir: 1.9
      otp_release: 22.0
    - elixir: 1.10
      otp_release: 22.0
    - elixir: 1.10
      otp_release: 23.0
      script:
        - mix format --check-formatted
        - mix dialyzer
        - mix credo
        - mix coveralls.travis --include conformance
        - MIX_ENV=prod mix compile --warnings-as-errors
before_script:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-x86_64.zip
  - unzip -d protoc protoc-3.12.3-linux-x86_64.zip
  - export PATH=$PWD/protoc/bin/:$PATH
  - wget https://github.com/ahamez/protox/releases/download/0.20.0/conformance-linux-x86_64.zip
  - unzip conformance-linux-x86_64.zip
env:
  - MIX_ENV=test PROTOBUF_CONFORMANCE_RUNNER=./conformance/conformance-test-runner LD_LIBRARY_PATH=./conformance/.libs
script:
  - mix dialyzer
  - mix credo
  - mix coveralls.travis --include conformance
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
notifications:
  email:
    - alexandre.hamez+travis@gmail.com
cache:
  directories:
    - priv/plts
